spring.application.name=projectFlow


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

secret.jwt.key=${JWT_SECRET}
secret.jwt.expiration=${JWT_EXPIRATION:86400000}

frontend.url=${FRONTEND_URL}